In [8]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [9]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [10]:
# target = label, 지도학습의 레이블 값 iris.keys()로 확인가능
# -> 붓꽃은 분류하는것이 목적 (0,1,2)

In [19]:
import pandas as pd
iris = load_iris()
iris_data = iris.data
iris_lable = iris.target

iris_df = pd.DataFrame(data= iris_data, columns = iris.feature_names)
iris_df['lable'] = iris.target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   lable  
0      0  
1      0  
2      0  
3      0  
4      0

In [12]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [13]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

레이블값 = 내가 구하고싶은거, 그래서 이 꽃의 이름은? 0임?1임?2임? (독립변수. 0,1,2)
feature_names = 종속변수들의 이름. 꽃 구분하기 위한 값들(feature)의 이름(name)

In [15]:
iris_data = load_iris()

print('feature_names 의 type:', type(iris_data.feature_names))
print(' feature_names 의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names 의 type:', type(iris_data.target_names))
print(' feature_names 의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 의 type:', type(iris_data.data))
print(' data 의 shape:', iris_data.data.shape)
print(iris_data['data'])

print('\n target 의 type:', type(iris_data.target))
print(' target 의 shape:', iris_data.target.shape)
print(iris_data.target)

feature_names 의 type: <class 'list'>
 feature_names 의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names 의 type: <class 'numpy.ndarray'>
 feature_names 의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 의 type: <class 'numpy.ndarray'>
 data 의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.

In [16]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   lable              150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [20]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_lable, test_size = 0.2, random_state =11)

In [21]:
len(X_train)

120

X_train과 X_test는 데이터셋을 학습 데이터셋과 검증 데이터셋으로 나누는 과정에서 사용되는 변수들입니다. 보통 지도학습 모델을 만들 때, 데이터셋을 학습용과 검증용으로 나누어서 모델을 만들고 검증을 수행합니다. 학습용 데이터셋을 사용하여 모델을 학습하고, 검증용 데이터셋을 사용하여 모델의 성능을 평가합니다.

X_train은 학습용 데이터셋에서 입력(input) 데이터를 의미하며, Y_train은 학습용 데이터셋에서 출력(output) 데이터를 의미합니다. 이때, 입력 데이터와 출력 데이터는 대응되는 데이터들끼리 함께 묶여 있습니다. 학습용 데이터셋에서는 입력 데이터와 출력 데이터가 모두 주어지므로, 모델은 입력 데이터와 출력 데이터의 관계를 학습할 수 있습니다.

X_test는 검증용 데이터셋에서 입력 데이터를 의미하며, Y_test는 검증용 데이터셋에서 출력 데이터를 의미합니다. 검증용 데이터셋에서는 입력 데이터만 주어지고, 모델이 예측한 출력 데이터와 실제 출력 데이터를 비교하여 모델의 성능을 평가합니다.

따라서, X_train, X_test, Y_train, Y_test는 지도학습 모델을 만들기 위해 사용되는 데이터셋에서 입력과 출력을 나타내는 변수들입니다. 이들을 이용하여 모델을 학습하고, 검증하여 모델의 성능을 평가할 수 있습니다.

In [6]:
# ==> 결과를 알게 되면 어떻게 써먹을 수 있을까? 품종개량 및 효율적 관리에 용이(smart farm...)

In [22]:
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

#학습 수행(fit)
dt_clf.fit(X_train ,y_train)

DecisionTreeClassifier(random_state=11)

In [23]:
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 세트로 예측 수행.
pred = dt_clf.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


In [32]:
iris = load_iris()
iris_data = iris.data
iris_lable = iris.target

iris_df = pd.DataFrame(data= iris_data, columns = iris.feature_names)
iris_df['lable'] = iris.target

X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_lable, test_size = 0.2, random_state =11)

dt_clf = DecisionTreeClassifier(random_state=11)

dt_clf.fit(X_train ,y_train)

pred = dt_clf.predict(X_test)

print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333
