#### NumPy는 “Numerical Python“의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공
* Numerical Python을 의미하는 NumPy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
* 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
* 넘파이의 기본 데이터 타입은 ndarray. ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

NumPy 특징

- 강력한 N 차원 배열 객체
- 정교한 브로드케스팅(Broadcast) 기능
- C/C ++ 및 포트란 코드 통합 도구
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환(Fourier transform, FT)은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

Numpy Documentation  

https://numpy.org/doc/1.21/index.html


Numpy는 대용량 데이터 배열을 효율적으로 다룰 수 있도록 설계되었다.
- Numpy는 내부적으로 데이터를 다른 내장 파이썬 객체와 구분된 연속된 메모리 블록에 저장
- Numpy의 각종 알고리즘은 모두 C로 작성되어 타입 검사나 다른 오버헤드 없이 메모리를 직접 조작
- Numpy 배열은 또한 내장 파이썬의 연속된 자료형들보다 훨씬 더 적은 메모리를 사용
- Numpy 연산은 파이썬 반복문을 사용하지 않고 전체 배열에 대한 복잡한 계산을 수행

In [4]:
# 리스트랑 배열 비교해볼거임
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

# 연산 시간 체크
%time for _ in range(10): my_arrar2 = my_arr * 2

Wall time: 20.6 ms


In [5]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]
    
    #결과 = 배열이 굉장히 효과적이다 !

Wall time: 754 ms


In [14]:
# 배열간 연산 가능한!
np.random.seed(0)
data = np.random.randn(2,3)
print(data,'\n')
print(data*10,'\n')
print(data + data)

[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]] 

[[17.64052346  4.00157208  9.78737984]
 [22.40893199 18.6755799  -9.7727788 ]] 

[[ 3.52810469  0.80031442  1.95747597]
 [ 4.4817864   3.73511598 -1.95455576]]


In [16]:
# 데이터 정보 확인

print(data.shape) #데이터의 크기 확인 (몇 행 몇 열인지)
print(data.dtype) #데이터의 자료형 확인
print(data.ndim) #데이터의 차원 확인


(2, 3)
float64
2


In [24]:
# 배열 생성
# 1차원

data1 = [6,7,5,8,0,1]
arr1 = np.array(data1)
print(arr1, type(arr1))
print(arr1.ndim)

[6 7 5 8 0 1] <class 'numpy.ndarray'>
1


In [22]:
# 2차원
data2 = [[1,2,3,4],[5,6,7,8]]
arr2= np.array(data2)
print(arr2, type(arr2)) # 배열의 타입은 array
print(arr2.shape)
print(arr2.dtype) # 데이터 타입은 정수
print(arr2.ndim)

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>
(2, 4)
int32
2


In [26]:
# 3차원

data3 = [[[1,2,3,4,5],[6,7,8,9,10]],
        [[1,2,3,4,5],[6,7,8,9,10]],
        [[1,2,3,4,5],[6,7,8,9,10]]]
        
array3 = np.array(data3)
print(array3, type(array3))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]] <class 'numpy.ndarray'>


배열 생성 및 초기화
- Numpy는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [32]:
# 원소가 0인걸 10개짜리 만들어주는거

#print(np.zeros(10))
#print(np.zeros((3,5)))
print(np.zeros((2,3,4))) #3행 4열짜리 2개

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [33]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [2]:
# 과제) zeros_like, ones_like, full_like함수 사용 예를 작성하세요.
data = np.random.randint(1,11, size=(3,3))
print(data)

# arr = np. 

NameError: name 'np' is not defined

In [7]:
import numpy as np
a=np.arange(10).reshape(2,5)
print(a,'\n')

print(np.zeros_like(a),'\n')
print(np.ones_like(a),'\n')
print(np.full_like(a,8))

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[0 0 0 0 0]
 [0 0 0 0 0]] 

[[1 1 1 1 1]
 [1 1 1 1 1]] 

[[8 8 8 8 8]
 [8 8 8 8 8]]


In [34]:
a= np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
# arange함수 : 파이썬의 range 함수의 배열 버전
ar = np.arange(15)
ar


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
#reshape함수 우리가 원하는 차원으로 바꿀 수 있음 나누어떨어지도록!
ar.reshape(1,15)  # 대괄호가 두 개 있으니까 2차원
ar.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
# array1에 reshape 함수를 이용하여 (5,2)배열을 생성하고 형태를 같이 출력하세요.
array1 = np.arange(10)
array1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [52]:
# ar에 reshape() 함수 이용, 1,2,3차원 배열 생성

ar = np.arange(24)
print(ar)
print(ar.reshape(4,6))
print(ar.reshape(2,3,4))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [227]:
# 1 -> 2,3차원 변경 -1 사용 , -1은 니가 알아서 해줘
ar1 = np.arange(30)

ar12 = ar1.reshape(2,-1)
ar13 = ar1.reshape(-1,2,5)

print(ar13)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [228]:
# 2 -> 1,3차원 변경 -1 사용

print(ar12)
ar21 = ar12.reshape(-1,)
ar23 = ar12.reshape(-1,2,5)

print(ar21,'\n')
print(ar23)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [234]:
# 3-> 1,2차원 변경 -1 사용

ar31 = ar13.reshape(-1,)
ar32 = ar13.reshape(3,-1)
print(ar31,'\n')
print(ar32)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [69]:
ar3 = np.arange(30).reshape(3,2,5)
print(ar3, type(ar3),'\n')

l3=ar3.tolist()
print(l3)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] <class 'numpy.ndarray'> 

[[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]], [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]]]


행렬의 종류

https://math-development-geometry.tistory.com/52

- 정방행렬은 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 삼각행렬은 주대각선 원소를 기준으로 위 또는 아래에 있는 성분이 모두 0인 정방행렬
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을때 항등행렬이 나오는 행렬

In [71]:
# 정방행렬

a = np.full((2,2),7)
a

array([[7, 7],
       [7, 7]])

In [72]:
# 항등행렬, 단위행렬 eye함수 대각선의 개수가 3 
ar = np.eye(3)
ar

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
# 대각행렬 대각선에 들어가는 숫자
diag_mat = np.diag([1,2,3,4,5])
diag_mat

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [75]:
# 삼각행렬

upper_tri_mat = np.triu([[1,2,3],[4,5,6],[7,8,9]])
print(upper_tri_mat)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [77]:
# 과제) 하삼각행렬을 생성하세요

lower_tri_mat = np.tril([[1,2,3],[4,5,6],[7,8,9]])
print(lower_tri_mat)

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [84]:
# 전치행렬 : 원래 행렬에서 행과 열을 바꾼 행렬


mat = np.array([[1,2],[3,4],[5,6]])
print(mat,'\n')

transpose_mat = mat.T
print(transpose_mat)

[[1 2]
 [3 4]
 [5 6]] 

[[1 3 5]
 [2 4 6]]


직교행렬

- 행과 열이 서로 직교하는 정방행렬. 
- 모든 열벡터와 행벡터가 서로 직교하교 크기가 1인 단위벡터로 이루어짐.
- np.linalg.qr() 함수를 사용한다. qr분행을 수행하여 직교행렬을 추출.
- q를 추출하여 직교행렬을 만든다.
- np.dot(orth_mat,orth_mat.T)을 계산하여 직교성을 검증한다.  (나중에 배울거임)
- np.allclose()함수로 두 행렬이 동일한지 검사한다. True를 반환하면 두 행렬은 동일.

In [90]:
mat = np.random.randn(3,3)
print(mat)

# qr분해 후 q추출, 지표에 있는 orth mat을 만든다.
q,r = np.linalg.qr(mat)

# 직교행렬 추출
orth_mat = q
print(orth_mat)

# 직교성 검증 -> allclose 뒤에 두개가 같은지 검사하는 과정
print(np.allclose(np.dot(orth_mat, orth_mat.T),np.eye(3)))



[[-1.70627019  1.9507754  -0.50965218]
 [-0.4380743  -1.25279536  0.77749036]
 [-1.61389785 -0.21274028 -0.89546656]]
[[-0.71418111  0.58409529 -0.38571756]
 [-0.18336158 -0.68793021 -0.70223255]
 [-0.67551749 -0.43079544  0.59840739]]
True


#### 배열의 인덱싱, 슬라이싱

In [91]:
ar2 = np.arange(1,10).reshape(3,3)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
# 7,8,9 뽑기 loc, iloc 안 써도 됨ㅋ 2번째 행이므로

ar2[2]

array([7, 8, 9])

In [95]:
# 3 뽑기
#ar2[0][2]
ar2[0,2]

3

In [127]:
# 슬라이싱
ar = np.arange(20).reshape(5,4)
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [125]:
ar[:2,1:]

array([[2, 3],
       [5, 6]])

In [128]:
ar[2,1]

9

In [122]:
# ar에서 슬라이싱을 사용하여 아래와 같이 출력하세요
ar = np.arange(1,10).reshape(3,3)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
print(ar[:2,:2],'\n')
print(ar[1:],'\n')
print(ar[1:,:],'\n')
print(ar,'\n')
print(ar[:2,1:],'\n')
print(ar[:2,0])

[[1 2]
 [4 5]] 

[[4 5 6]
 [7 8 9]] 

[[4 5 6]
 [7 8 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[2 3]
 [5 6]] 

[1 4]


In [ ]:
#과제) ar에서 인덱스를 이용해서 값을 선택하고 리스트로 아래와 같이 출력하세요.
[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]

In [9]:
ar = np.arange(1,10).reshape(3,3)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print(ar[:2,2].tolist(),'\n')
print(ar[:2,:2].tolist(),'\n')
print(ar[:2].tolist())

[3, 6] 

[[1, 2], [4, 5]] 

[[1, 2, 3], [4, 5, 6]]


In [114]:
# Boolean indexing

ar = np.arange(1,10)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
ar[ar> 5]
# 이 안의 조건이 참인것만 반환한다

array([6, 7, 8, 9])

In [133]:
# 1~14까지 ndarray를 만들어 array_e로 저장하고 (array_e/2)>5를 만족하는 값을 불린 인덱스로 출력.

array_e = np.arange(1,15)


array_e[array_e/2>5]

array([11, 12, 13, 14])

In [138]:
# arr 에서 0.5보다 큰 수를 출력하세요.
np.random.seed(0)
arr = np.random.randn(30)
print(arr)
arr[arr>0.5]

[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
  0.95008842 -0.15135721 -0.10321885  0.4105985   0.14404357  1.45427351
  0.76103773  0.12167502  0.44386323  0.33367433  1.49407907 -0.20515826
  0.3130677  -0.85409574 -2.55298982  0.6536186   0.8644362  -0.74216502
  2.26975462 -1.45436567  0.04575852 -0.18718385  1.53277921  1.46935877]


array([1.76405235, 0.97873798, 2.2408932 , 1.86755799, 0.95008842,
       1.45427351, 0.76103773, 1.49407907, 0.6536186 , 0.8644362 ,
       2.26975462, 1.53277921, 1.46935877])

In [141]:
# data에서 3의 배수인 것만 출력하세요.
# np.random.seed(0)
data = np.arange(30)
data[data%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [249]:
# 과제) [1,2,0,0,4,0]에서 zero가 아닌 **인덱스**를 배열형태로 출력하세요.

list = [1,2,0,0,4,0]
arr1 = np.array(list)

arr1[arr1!=0]

array([1, 2, 4])

np.where(condition)은 
- condition 배열의 요소가 True인 인덱스를 반환하는 함수입니다. 
- condition 배열은 bool 타입이어야 하며, 반환값은 tuple 타입으로 (array of row indices, array of column indices)의 형태로 반환

In [ ]:
np.where(a!=0,1,0)

In [13]:
# 김나영
#과제: 0이 아닌 값 인덱스를 배열형태로 출력
a=np.array([1,2,0,0,4,0])

index=np.where(a!=0)     #조건을 만족하는 인덱스 반환.(결과값을 안 주면 t/f로 해서 true의 인덱스값 반환)
print(index)
print(index[0])           #[0]에 인덱스 값, [1]에 타입값

(array([0, 1, 4], dtype=int64),)
[0 1 4]


In [20]:
# 선생님
a = np.array([1,2,0,0,4,0])
nz = np.nonzero(a) #a에서 0이 아닌 걸 인덱스로 뽑아준다
print(nz)
print(nz[0])

(array([0, 1, 4], dtype=int64),)
[0 1 4]


In [145]:
bools = np.array([False, False, True, True])
bools


array([False, False,  True,  True])

In [146]:
# any 메소드: 하나 이상의 값이 True 인지 검사
bools.any()

True

In [147]:
# all 메소드 : 모든 원소가 True 인지 검사
bools.all()

False

In [153]:
# arr에서 0보다 크면 2로, 아니면 -2로 변경하세요.
arr = np.random.randn(4,4)
print(arr)

np.where(arr>0,2,-2)

[[-1.16514984  0.90082649  0.46566244 -1.53624369]
 [ 1.48825219  1.89588918  1.17877957 -0.17992484]
 [-1.07075262  1.05445173 -0.40317695  1.22244507]
 [ 0.20827498  0.97663904  0.3563664   0.70657317]]


array([[-2,  2,  2, -2],
       [ 2,  2,  2, -2],
       [-2,  2, -2,  2],
       [ 2,  2,  2,  2]])

In [166]:
# arr의 모든 양수를 2로 바꾸세요.
print(arr)
np.where(arr>0,2,arr)

[[-1.16514984  0.90082649  0.46566244 -1.53624369]
 [ 1.48825219  1.89588918  1.17877957 -0.17992484]
 [-1.07075262  1.05445173 -0.40317695  1.22244507]
 [ 0.20827498  0.97663904  0.3563664   0.70657317]]


array([[-1.16514984,  2.        ,  2.        , -1.53624369],
       [ 2.        ,  2.        ,  2.        , -0.17992484],
       [-1.07075262,  2.        , -0.40317695,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ]])

In [169]:
# np.sort() : 복사본을 반환
np.random.seed(0)
arr = np.random.randint(1,100,size=10)
arr

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [170]:
print(np.sort(arr)) #원본 반영 안 됨 -> sorted에 새로 지정해야함
print(arr)

[10 22 37 45 48 65 68 68 84 88]
[45 48 65 68 68 10 84 22 37 88]


In [171]:
sorted = np.sort(arr)
print(sorted)

[10 22 37 45 48 65 68 68 84 88]


In [181]:
# 행렬이 2차원 이상일 경우, axis 축 값 설정을 통해 로우방향, 칼럼방향으로 정렬 수행
ar2 = np.array([[8,12], [7,1]])
print(np.sort(ar2,axis=0),'\n')
print(np.sort(ar2,axis=1))

[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]]


In [251]:
ar2 = np.array([[8,12,10], [7,1,2]])
print(np.sort(ar2,axis=0),'\n')
print(np.sort(ar2,axis=1))

[[ 7  1  2]
 [ 8 12 10]] 

[[ 8 10 12]
 [ 1  2  7]]


In [259]:
# ndarray.sort() : 원본 반영
np.random.seed(0)
arr = np.random.randint(10,size=10)
print(arr.sort())
print(arr)
arr.sort()
arr

None
[0 2 3 3 3 4 5 5 7 9]


array([0, 2, 3, 3, 3, 4, 5, 5, 7, 9])

In [260]:
np.random.seed(0)
arr = np.random.randint(10,size=(10,10))
arr

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1, 6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6, 8, 4, 1, 4, 9],
       [8, 1, 1, 7, 9, 9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
       [4, 4, 8, 4, 3, 7, 5, 5, 0, 1],
       [5, 9, 3, 0, 5, 0, 1, 2, 4, 2]])

In [261]:
# 방향 정해주기 1은 열, 0은 행
arr.sort(0)
arr

array([[0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 1, 1, 1, 3, 3, 1, 2, 0, 0],
       [2, 3, 3, 3, 3, 3, 2, 3, 2, 1],
       [4, 3, 3, 4, 4, 3, 3, 4, 2, 1],
       [5, 4, 5, 4, 4, 4, 3, 5, 4, 1],
       [5, 4, 5, 5, 5, 6, 3, 5, 4, 2],
       [5, 6, 8, 7, 6, 7, 4, 6, 4, 2],
       [7, 9, 8, 8, 7, 8, 5, 7, 5, 3],
       [8, 9, 8, 9, 7, 9, 6, 7, 7, 4],
       [9, 9, 8, 9, 9, 9, 7, 7, 8, 9]])

In [262]:
arr.sort(1)
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 2, 3, 3],
       [1, 2, 2, 2, 3, 3, 3, 3, 3, 3],
       [1, 2, 3, 3, 3, 3, 4, 4, 4, 4],
       [1, 3, 4, 4, 4, 4, 4, 5, 5, 5],
       [2, 3, 4, 4, 5, 5, 5, 5, 5, 6],
       [2, 4, 4, 5, 6, 6, 6, 7, 7, 8],
       [3, 5, 5, 7, 7, 7, 8, 8, 8, 9],
       [4, 6, 7, 7, 7, 8, 8, 9, 9, 9],
       [7, 7, 8, 8, 9, 9, 9, 9, 9, 9]])

In [200]:
# 정렬된 행렬의 인덱스 반환 : 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(org_array)
sort_indices

[3 1 9 5]


array([1, 0, 3, 2], dtype=int64)

In [201]:
# 배열도 입출력이 있다... 어떻게 하느냐~~~~~~~~~~~~~!!!!!!! 
#np.save & np.load, 바이너리 형식, npy파일로 저장

arr= np.arange(10)
np.save('some_array',arr)

np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [202]:
# np.savez : 여러 개의 배열을 압축된 형식으로 저장
np.savez('array_archive.npz',a=arr, b=arr)
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [210]:
# 인덱싱을 사용하여 [ 1 0 1 0 1 0 1 0 1 0 ]을 출력하세요.

arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[:] = arr%2
arr

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [212]:
a = np.ones(10,dtype=int)
a[[1,3,5,7,9]] = 0
print(a)

[1 0 1 0 1 0 1 0 1 0]


#### [과제] 1 ~ 100을 아래와 같이 출력하세요

In [ ]:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>

In [380]:
arr=np.arange(1,101).reshape(10,10)
print(arr[0])
print(arr[1][::-1])
print(arr[2])
print(arr[3][::-1])
print(arr[4])
print(arr[5][::-1])
print(arr[6])
print(arr[7][::-1])
print(arr[8])
print(arr[9][::-1],type(arr))


[ 1  2  3  4  5  6  7  8  9 10]
[20 19 18 17 16 15 14 13 12 11]
[21 22 23 24 25 26 27 28 29 30]
[40 39 38 37 36 35 34 33 32 31]
[41 42 43 44 45 46 47 48 49 50]
[60 59 58 57 56 55 54 53 52 51]
[61 62 63 64 65 66 67 68 69 70]
[80 79 78 77 76 75 74 73 72 71]
[81 82 83 84 85 86 87 88 89 90]
[100  99  98  97  96  95  94  93  92  91] <class 'numpy.ndarray'>


In [23]:
arr = np.arange(1,101).reshape(10,10)
print(arr)
arr[1::2] = arr[1::2, ::-1]
print(arr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


#### [과제] np.ones((10,10))을 아래와 같이 출력하세요

In [ ]:
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
arr = np.ones((10,10))
arr
arr[1:9,1:9] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### [과제] np.ones((5,5))을 아래와 같이 출력하세요

In [ ]:
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [266]:
arr = np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
arr = np.zeros((10,10))
arr[2:8,2:8] = 1
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
#과제: 전부 1인 5x5배열을 -> 9x9배열로 확장, 0 채우기
arr=np.ones((5,5))

v=np.zeros((2,5))
h=np.zeros((9,2))

arr2=np.vstack((arr,v))      # arr 아래에 v 붙이기
arr2=np.vstack((v,arr2))
#print(arr2)

arr2=np.hstack((h,arr2))     # h 옆에 arr2 붙이기
arr2=np.hstack((arr2,h))
print(arr2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [1]:
import numpy as np

arr = np.ones((5, 5))
arr = np.pad(arr, ((2, 2), (2, 2)), mode='constant')  # 모서리에 0을 추가

arr[2:7, 2:7] = 1  # 중앙 부분 1로 변경

print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### [과제] np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)

In [ ]:
array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [352]:
arr=np.zeros((8,8))
arr[0,[1,3,5,7]] =1
arr[1,[0,2,4,6]] =1
arr[2,[1,3,5,7]] =1
arr[3,[0,2,4,6]] =1
arr[4,[1,3,5,7]] =1
arr[5,[0,2,4,6]] =1
arr[6,[1,3,5,7]] =1
arr[7,[0,2,4,6]] =1
arr


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [3]:
arr = np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if (i + j) % 2 != 0:
            arr[i][j] = 1
print(arr,'\n')

arr = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]] 

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [31]:
#과제: 전부 0인 배열을 패턴화해서 출력
arr=np.zeros((8,8))

for i in range(8):
    if i%2==0:
        arr[i][1::2]=1     # 짝수 번째 줄 0101010
    else:
        arr[i][0::2]=1     # 홀수 번째 줄 1010101
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [277]:
arr = np.array([0,1])
np.tile(a,(8,1))

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

In [32]:
# 선생님
z= np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### [과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요

In [213]:
np.arange(336).reshape(6,7,8)

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [6]:
#[과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스 구하기
arr=np.arange(336).reshape(6,7,8)

b=arr.reshape(-1)
idx=np.where(arr==b[99])     #b의 99인덱스 = arr의 100번째

index=[idx[i][0] for i in range(len(idx))]    #인덱스값 뽑기
print(index)
idx

[1, 5, 3]


(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))

In [5]:
# unravel_index() 함수는 1차원 배열에서 인덱스를 다차원 인덱스 튜플로 반환해주는 함수
arr = np.arange(336).reshape(6,7,8)
np.unravel_index(100, arr.shape)

(1, 5, 4)