연산

시리즈끼리는(?) 브로드캐스팅이 된다
근데 df랑 sr도 연산 적용이 된다.

df2는 대괄호 두 번 해줘야 함.(한 번 하면 에러,  2차원이므로 대괄호 두 번)

nan값이 나온다 -> 브로드캐스팅이 안 된거다.
브로드 캐스팅이 된거면 값이 확대가 되어야하는데 안 나왓다 -> gpt의 오류

-> 시리즈로 바꿔서 실행(iloc)
시리즈는 하나의 행이니까 브로드캐스팅이 되므로, 시리즈 바꿔서 실행

*데이터프레임끼리는 브로드캐스팅이 안 된다.*

map 시리즈
apply df 및 여러개에서 적용
applymap은 각 요소벌로 작동
이거 정리해둔거 있으니까 보고 새로 정리하기


In [ ]:
# chatGPT 에러 : pandas broadcasting 적용 사례

import pandas as pd
import numpy as np

# 3x3 행렬 생성
df1 = pd.DataFrame(np.arange(1, 10).reshape(3, 3), columns=list('ABC'))

# 1x3 행렬 생성
df2 = pd.DataFrame([[10, 20, 30]], columns=list('ABC'))

# df1 출력
print("df1:\n", df1)

# df2 출력
print("\ndf2:\n", df2)

# df1과 df2의 합 구하기
result = df1 + df2

# result 출력
print("\nresult:\n", result)

In [ ]:
import pandas as pd
import numpy as np

# 3x3 행렬 생성
df1 = pd.DataFrame(np.arange(1, 10).reshape(3, 3), columns=list('ABC'))

# 1x3 행렬 생성
df2 = pd.DataFrame([[10, 20, 30]], columns=list('ABC'))
sr2 = df2.iloc[0]
# df1 출력
print("df1:\n", df1)

# df2 출력
print("\nsr2:\n", sr2)

In [ ]:
# df1과 sr2의 합 구하기
result = df1 + sr2

# result 출력
print("\nresult:\n", result)

In [ ]:
브로드캐스팅 정리하기

In [9]:
# 시리즈도 연산할 수 있다.
import pandas as pd
st1 = pd.Series({'국어':100, '영어':80, '수학':90})
st2 = pd.Series({'국어':90, '영어':80, '수학':80})

add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)

print(add,'\n')
print(sub,'\n')
# print(mul,'\n')
# print(div)

국어    190
영어    160
수학    170
dtype: int64 

국어    10
영어     0
수학    10
dtype: int64 



In [4]:
# 연산 한걸 데이터프레임으로 표시
# concat으로 합쳐지는 것은 axis가 기준이 된다. [add,sub,mul,div]가 열(1)이 됨
# 파이썬에서 axis = 1은 2차원 배열(또는 데이터프레임)의 열(column) 방향(axis)을 나타냅니다.
df = pd.concat([add,sub,mul,div], axis=1)
df

0   1     2     3
국어  190  10  9000  1.11
영어  160   0  6400  1.00
수학  170  10  7200  1.12

In [7]:
df = pd.concat([add,sub,mul,div], axis=0)
df
# -> 이건 표현을 할 때 행 방향으로 더해서 표현을 한 것,
# 국어합
# 영어합
# 수학합
# 국어차
# 영어차
# 수학차
# 국어곱
# 영어곱
# 수학곱
# 국어나
# 영어나
# 수학나

국어     190.00
영어     160.00
수학     170.00
국어      10.00
영어       0.00
수학      10.00
국어    9000.00
영어    6400.00
수학    7200.00
국어       1.11
영어       1.00
수학       1.12
dtype: float64

In [11]:
# 여기서는 add 어쩌고들이 인덱스행이 되었다.
# 인덱스 안 주면 행 열 바뀜, 인덱스 줘서 덧셈뺄셈이 행으로 감(위의 예시)
result = pd.DataFrame([add,sub,mul,div],index=['덧셈','뺄셈','곱셈','나눗셈'])
result

국어      영어       수학
덧셈    190.00   160.0   170.00
뺄셈     10.00     0.0    10.00
곱셈   9000.00  6400.0  7200.00
나눗셈     1.11     1.0     1.12

In [ ]:
df로 바꾸기

In [ ]:
import pandas as pd
st1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
st2 = pd.Series({'수학':80, '국어':90})

In [15]:
import pandas as pd
import numpy as np
st1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
st2 = pd.Series({'수학':80, '국어':90})

add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)

print(add,'\n')
print(sub,'\n')
print(mul,'\n')
print(div)

result = pd.DataFrame([add,sub,mul,div],index=['덧셈','뺄셈','곱셈','나눗셈'])
result

국어      NaN
수학    170.0
영어      NaN
dtype: float64 

국어     NaN
수학    10.0
영어     NaN
dtype: float64 

국어       NaN
수학    7200.0
영어       NaN
dtype: float64 

국어     NaN
수학    1.12
영어     NaN
dtype: float64


국어       수학  영어
덧셈  NaN   170.00 NaN
뺄셈  NaN    10.00 NaN
곱셈  NaN  7200.00 NaN
나눗셈 NaN     1.12 NaN

In [16]:
# 1차원 배열
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
# 2차원 배열. 3행 4열
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
df1 = pd.DataFrame(np.arange(12).reshape((3,4)), columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20).reshape((4,5)), columns = list('abcde')) #일부러 행렬이 맞지 않게

print(df1, '\n')
print(df2)

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11 

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19


In [20]:
# 실수화 (.)
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns = list('abcde')) #일부러 행렬이 맞지 않게

print(df1, '\n')
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0 

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [21]:
# nan값 처리
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns = list('abcde')) #일부러 행렬이 맞지 않게

df2.loc[1,'b'] = np.nan
print(df1, '\n')
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0 

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [22]:
df1 + df2
# null값이 있으면 계산이 되지 않으므로 nan으로 나옴

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [10]:
# fill_value()
# Q. df2의 Nan값을 0으로 대체 후 사칙연산을 수행하세요.

add_data = df1.add(df2,fill_value=0)
sub_data = df1.sub(df2, fill_value=0)
mul_data = df1.mul(df2, fill_value=0)
div_data = df1.div(df2, fill_value=0)

print(add_data,'\n')
print(sub_data,'\n')
print(mul_data,'\n')
print(div_data)

NameError: name 'df1' is not defined

In [25]:
arr = np.arange(12.).reshape(3,4)
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [26]:
arr[0]

array([0., 1., 2., 3.])

In [2]:
# GPT 에러 예시

In [27]:
# broadcasting 같은 행만큼 확대해서 처리해준다.
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [28]:
# DataFrame과 Series간 연산
df = pd.DataFrame(np.arange(12.).reshape(4,3), columns = list('bde'),
                 index = ['서울','부산','인천','대구'])
df

b     d     e
서울  0.0   1.0   2.0
부산  3.0   4.0   5.0
인천  6.0   7.0   8.0
대구  9.0  10.0  11.0

In [29]:
sr = df.iloc[0]
sr

b    0.0
d    1.0
e    2.0
Name: 서울, dtype: float64

In [30]:
# df에서 sr빼도 처리가 됨
df - sr

b    d    e
서울  0.0  0.0  0.0
부산  3.0  3.0  3.0
인천  6.0  6.0  6.0
대구  9.0  9.0  9.0

In [31]:
# 함수 적용과 maping
# randn : 표준정규분포에서 난수 생성 -> 음수도 포함

df = pd.DataFrame(np.random.randn(4,3), columns = list('bde'),
                 index = ['서울','부산','인천','대구'])
df

b         d         e
서울 -1.198379 -0.921464 -1.130840
부산  1.259366  0.797212  0.356988
인천 -0.123643  1.057454 -0.796557
대구  0.511809  0.251588 -1.163709

In [32]:
# 절댓값 -> 각각 매핑하여 결과 절대값으로 출력
np.abs(df)

b         d         e
서울  1.198379  0.921464  1.130840
부산  1.259366  0.797212  0.356988
인천  0.123643  1.057454  0.796557
대구  0.511809  0.251588  1.163709

커스텀 함수(custom function)를 DataFrame에 적용하려면 map함수, apply함수, applymap함수를 사용
- map함수 : DataFrame 타입이 아니라, 반드시 Series 타입에서만 사용
- apply함수 : 커스텀 함수를 사용하기 위해 DataFrame에서 복수 개의 컬럼이 필요하다면, apply함수를 사용
- applymap함수 : DataFrame클래스의 함수이긴 하나, 위의 apply함수처럼 각 row(axis=1)나 각 column(axis=0)별로 
작동하는 함수가 아니라, 각 요소(element)별로 작동  
마치 선형대수에서 벡터에 스칼라를 연산하면, 벡터의 요소 하나하나에 해당 연산을 해주는 것처럼(elementwise) 
적용하는 DataFrame의 각 요소마다 커스텀 함수(반드시 Single vaule를 반환하는)를 수행한다고 보면 된다. 
applymap에 인자로 전달하는 커스텀함수가 Single value로부터 Single value를 반환한다는 점이 중요하다

In [33]:
# series의 최대값과 최소값의 차이를 계산
f = lambda x:x.max() - x.min()
df.apply(f)

b    2.457745
d    1.978919
e    1.520696
dtype: float64

In [34]:
# 각 행에 대해서 수행 (디폴트가 열 방향이라 행으로 바꾸려면 axis설정해줘야 함)
df.apply(f,axis = 'columns')

서울    0.276915
부산    0.902379
인천    1.854012
대구    1.675518
dtype: float64

In [39]:
#적절한 사용자 함수 혹은 람다함수를 생성해서 df에 그 함수를 적용한 결과를 출력하세요.

a= lambda x:(x.max() + x.min())/2
df.apply(a, axis = 'index')

b    0.030494
d    0.067995
e   -0.403361
dtype: float64

In [41]:
# 여러 값을 가진 series 변환
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min','max'])

df.apply(f)

b         d         e
min -1.198379 -0.921464 -1.163709
max  1.259366  1.057454  0.356988

In [43]:
# 실수 값을 문자열 포맷으로 변환(소수점 2자리), 각 요소별로 작동한다.

format = lambda x : '%.2f' %x
df.applymap(format)

b      d      e
서울  -1.20  -0.92  -1.13
부산   1.26   0.80   0.36
인천  -0.12   1.06  -0.80
대구   0.51   0.25  -1.16

In [44]:
# map함수는 series에만 적용

df['e']

서울   -1.130840
부산    0.356988
인천   -0.796557
대구   -1.163709
Name: e, dtype: float64

In [45]:
# map함수는 series에만 적용

df['e'].map(format)

서울    -1.13
부산     0.36
인천    -0.80
대구    -1.16
Name: e, dtype: object